// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

import { IndexEncoder, c, b4a } from 'hyperdb/runtime';
import { version, getEncoding, setVersion } from './messages.js';

const versions = { schema: version, db: 1 };

// '@ghostdrive/sessions' collection key
const collection0_key = new IndexEncoder([IndexEncoder.STRING], { prefix: 0 });

function collection0_indexify(record) {
	const a = record.id;
	return a === undefined ? [] : [a];
}

// '@ghostdrive/sessions' value encoding
const collection0_enc = getEncoding('@ghostdrive/session/hyperdb#0');

// '@ghostdrive/sessions' reconstruction function
function collection0_reconstruct(schemaVersion, keyBuf, valueBuf) {
	const key = collection0_key.decode(keyBuf);
	setVersion(schemaVersion);
	const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf };
	const type = c.uint.decode(state);
	if (type !== 0) throw new Error('Unknown collection type: ' + type);
	collection0.decodedVersion = c.uint.decode(state);
	const record = collection0_enc.decode(state);
	record.id = key[0];
	return record;
}
// '@ghostdrive/sessions' key reconstruction function
function collection0_reconstruct_key(keyBuf) {
	const key = collection0_key.decode(keyBuf);
	return {
		id: key[0]
	};
}

// '@ghostdrive/sessions'
const collection0 = {
	name: '@ghostdrive/sessions',
	id: 0,
	version: 1,
	encodeKey(record) {
		const key = [record.id];
		return collection0_key.encode(key);
	},
	encodeKeyRange({ gt, lt, gte, lte } = {}) {
		return collection0_key.encodeRange({
			gt: gt ? collection0_indexify(gt) : null,
			lt: lt ? collection0_indexify(lt) : null,
			gte: gte ? collection0_indexify(gte) : null,
			lte: lte ? collection0_indexify(lte) : null
		});
	},
	encodeValue(schemaVersion, collectionVersion, record) {
		setVersion(schemaVersion);
		const state = { start: 0, end: 2, buffer: null };
		collection0_enc.preencode(state, record);
		state.buffer = b4a.allocUnsafe(state.end);
		state.buffer[state.start++] = 0;
		state.buffer[state.start++] = collectionVersion;
		collection0_enc.encode(state, record);
		return state.buffer;
	},
	trigger: null,
	reconstruct: collection0_reconstruct,
	reconstructKey: collection0_reconstruct_key,
	indexes: [],
	decodedVersion: 0
};

// '@ghostdrive/registrations' collection key
const collection1_key = new IndexEncoder([IndexEncoder.STRING, IndexEncoder.STRING], { prefix: 1 });

function collection1_indexify(record) {
	const arr = [];

	const a0 = record.sessionId;
	if (a0 === undefined) return arr;
	arr.push(a0);

	const a1 = record.target;
	if (a1 === undefined) return arr;
	arr.push(a1);

	return arr;
}

// '@ghostdrive/registrations' value encoding
const collection1_enc = getEncoding('@ghostdrive/registration/hyperdb#1');

// '@ghostdrive/registrations' reconstruction function
function collection1_reconstruct(schemaVersion, keyBuf, valueBuf) {
	const key = collection1_key.decode(keyBuf);
	setVersion(schemaVersion);
	const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf };
	const type = c.uint.decode(state);
	if (type !== 0) throw new Error('Unknown collection type: ' + type);
	collection1.decodedVersion = c.uint.decode(state);
	const record = collection1_enc.decode(state);
	record.sessionId = key[0];
	record.target = key[1];
	return record;
}
// '@ghostdrive/registrations' key reconstruction function
function collection1_reconstruct_key(keyBuf) {
	const key = collection1_key.decode(keyBuf);
	return {
		sessionId: key[0],
		target: key[1]
	};
}

// '@ghostdrive/registrations'
const collection1 = {
	name: '@ghostdrive/registrations',
	id: 1,
	version: 1,
	encodeKey(record) {
		const key = [record.sessionId, record.target];
		return collection1_key.encode(key);
	},
	encodeKeyRange({ gt, lt, gte, lte } = {}) {
		return collection1_key.encodeRange({
			gt: gt ? collection1_indexify(gt) : null,
			lt: lt ? collection1_indexify(lt) : null,
			gte: gte ? collection1_indexify(gte) : null,
			lte: lte ? collection1_indexify(lte) : null
		});
	},
	encodeValue(schemaVersion, collectionVersion, record) {
		setVersion(schemaVersion);
		const state = { start: 0, end: 2, buffer: null };
		collection1_enc.preencode(state, record);
		state.buffer = b4a.allocUnsafe(state.end);
		state.buffer[state.start++] = 0;
		state.buffer[state.start++] = collectionVersion;
		collection1_enc.encode(state, record);
		return state.buffer;
	},
	trigger: null,
	reconstruct: collection1_reconstruct,
	reconstructKey: collection1_reconstruct_key,
	indexes: [],
	decodedVersion: 0
};

// '@ghostdrive/invites' collection key
const collection2_key = new IndexEncoder([IndexEncoder.STRING, IndexEncoder.STRING], { prefix: 2 });

function collection2_indexify(record) {
	const arr = [];

	const a0 = record.sessionId;
	if (a0 === undefined) return arr;
	arr.push(a0);

	const a1 = record.capKey;
	if (a1 === undefined) return arr;
	arr.push(a1);

	return arr;
}

// '@ghostdrive/invites' value encoding
const collection2_enc = getEncoding('@ghostdrive/invite/hyperdb#2');

// '@ghostdrive/invites' reconstruction function
function collection2_reconstruct(schemaVersion, keyBuf, valueBuf) {
	const key = collection2_key.decode(keyBuf);
	setVersion(schemaVersion);
	const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf };
	const type = c.uint.decode(state);
	if (type !== 0) throw new Error('Unknown collection type: ' + type);
	collection2.decodedVersion = c.uint.decode(state);
	const record = collection2_enc.decode(state);
	record.sessionId = key[0];
	record.capKey = key[1];
	return record;
}
// '@ghostdrive/invites' key reconstruction function
function collection2_reconstruct_key(keyBuf) {
	const key = collection2_key.decode(keyBuf);
	return {
		sessionId: key[0],
		capKey: key[1]
	};
}

// '@ghostdrive/invites'
const collection2 = {
	name: '@ghostdrive/invites',
	id: 2,
	version: 1,
	encodeKey(record) {
		const key = [record.sessionId, record.capKey];
		return collection2_key.encode(key);
	},
	encodeKeyRange({ gt, lt, gte, lte } = {}) {
		return collection2_key.encodeRange({
			gt: gt ? collection2_indexify(gt) : null,
			lt: lt ? collection2_indexify(lt) : null,
			gte: gte ? collection2_indexify(gte) : null,
			lte: lte ? collection2_indexify(lte) : null
		});
	},
	encodeValue(schemaVersion, collectionVersion, record) {
		setVersion(schemaVersion);
		const state = { start: 0, end: 2, buffer: null };
		collection2_enc.preencode(state, record);
		state.buffer = b4a.allocUnsafe(state.end);
		state.buffer[state.start++] = 0;
		state.buffer[state.start++] = collectionVersion;
		collection2_enc.encode(state, record);
		return state.buffer;
	},
	trigger: null,
	reconstruct: collection2_reconstruct,
	reconstructKey: collection2_reconstruct_key,
	indexes: [],
	decodedVersion: 0
};

// '@ghostdrive/joins' collection key
const collection3_key = new IndexEncoder([IndexEncoder.STRING, IndexEncoder.STRING], { prefix: 3 });

function collection3_indexify(record) {
	const arr = [];

	const a0 = record.sessionId;
	if (a0 === undefined) return arr;
	arr.push(a0);

	const a1 = record.peerKey;
	if (a1 === undefined) return arr;
	arr.push(a1);

	return arr;
}

// '@ghostdrive/joins' value encoding
const collection3_enc = getEncoding('@ghostdrive/join/hyperdb#3');

// '@ghostdrive/joins' reconstruction function
function collection3_reconstruct(schemaVersion, keyBuf, valueBuf) {
	const key = collection3_key.decode(keyBuf);
	setVersion(schemaVersion);
	const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf };
	const type = c.uint.decode(state);
	if (type !== 0) throw new Error('Unknown collection type: ' + type);
	collection3.decodedVersion = c.uint.decode(state);
	const record = collection3_enc.decode(state);
	record.sessionId = key[0];
	record.peerKey = key[1];
	return record;
}
// '@ghostdrive/joins' key reconstruction function
function collection3_reconstruct_key(keyBuf) {
	const key = collection3_key.decode(keyBuf);
	return {
		sessionId: key[0],
		peerKey: key[1]
	};
}

// '@ghostdrive/joins'
const collection3 = {
	name: '@ghostdrive/joins',
	id: 3,
	version: 1,
	encodeKey(record) {
		const key = [record.sessionId, record.peerKey];
		return collection3_key.encode(key);
	},
	encodeKeyRange({ gt, lt, gte, lte } = {}) {
		return collection3_key.encodeRange({
			gt: gt ? collection3_indexify(gt) : null,
			lt: lt ? collection3_indexify(lt) : null,
			gte: gte ? collection3_indexify(gte) : null,
			lte: lte ? collection3_indexify(lte) : null
		});
	},
	encodeValue(schemaVersion, collectionVersion, record) {
		setVersion(schemaVersion);
		const state = { start: 0, end: 2, buffer: null };
		collection3_enc.preencode(state, record);
		state.buffer = b4a.allocUnsafe(state.end);
		state.buffer[state.start++] = 0;
		state.buffer[state.start++] = collectionVersion;
		collection3_enc.encode(state, record);
		return state.buffer;
	},
	trigger: null,
	reconstruct: collection3_reconstruct,
	reconstructKey: collection3_reconstruct_key,
	indexes: [],
	decodedVersion: 0
};

// '@ghostdrive/registrations-by-session' collection key
const index4_key = new IndexEncoder(
	[IndexEncoder.STRING, IndexEncoder.STRING, IndexEncoder.STRING],
	{ prefix: 4 }
);

function index4_indexify(record) {
	const arr = [];

	const a0 = record.sessionId;
	if (a0 === undefined) return arr;
	arr.push(a0);

	const a1 = record.sessionId;
	if (a1 === undefined) return arr;
	arr.push(a1);

	const a2 = record.target;
	if (a2 === undefined) return arr;
	arr.push(a2);

	return arr;
}

// '@ghostdrive/registrations-by-session'
const index4 = {
	name: '@ghostdrive/registrations-by-session',
	version: 1,
	id: 4,
	encodeKey(record) {
		return index4_key.encode(index4_indexify(record));
	},
	encodeKeyRange({ gt, lt, gte, lte } = {}) {
		return index4_key.encodeRange({
			gt: gt ? index4_indexify(gt) : null,
			lt: lt ? index4_indexify(lt) : null,
			gte: gte ? index4_indexify(gte) : null,
			lte: lte ? index4_indexify(lte) : null
		});
	},
	encodeValue: (record) => index4.collection.encodeKey(record),
	encodeIndexKeys(record, context) {
		return [index4_key.encode([record.sessionId, record.sessionId, record.target])];
	},
	reconstruct: (keyBuf, valueBuf) => valueBuf,
	offset: collection1.indexes.length,
	collection: collection1
};
collection1.indexes.push(index4);

// '@ghostdrive/invites-by-session' collection key
const index5_key = new IndexEncoder(
	[IndexEncoder.STRING, IndexEncoder.STRING, IndexEncoder.STRING],
	{ prefix: 5 }
);

function index5_indexify(record) {
	const arr = [];

	const a0 = record.sessionId;
	if (a0 === undefined) return arr;
	arr.push(a0);

	const a1 = record.sessionId;
	if (a1 === undefined) return arr;
	arr.push(a1);

	const a2 = record.capKey;
	if (a2 === undefined) return arr;
	arr.push(a2);

	return arr;
}

// '@ghostdrive/invites-by-session'
const index5 = {
	name: '@ghostdrive/invites-by-session',
	version: 1,
	id: 5,
	encodeKey(record) {
		return index5_key.encode(index5_indexify(record));
	},
	encodeKeyRange({ gt, lt, gte, lte } = {}) {
		return index5_key.encodeRange({
			gt: gt ? index5_indexify(gt) : null,
			lt: lt ? index5_indexify(lt) : null,
			gte: gte ? index5_indexify(gte) : null,
			lte: lte ? index5_indexify(lte) : null
		});
	},
	encodeValue: (record) => index5.collection.encodeKey(record),
	encodeIndexKeys(record, context) {
		return [index5_key.encode([record.sessionId, record.sessionId, record.capKey])];
	},
	reconstruct: (keyBuf, valueBuf) => valueBuf,
	offset: collection2.indexes.length,
	collection: collection2
};
collection2.indexes.push(index5);

// '@ghostdrive/joins-by-session' collection key
const index6_key = new IndexEncoder(
	[IndexEncoder.STRING, IndexEncoder.STRING, IndexEncoder.STRING],
	{ prefix: 6 }
);

function index6_indexify(record) {
	const arr = [];

	const a0 = record.sessionId;
	if (a0 === undefined) return arr;
	arr.push(a0);

	const a1 = record.sessionId;
	if (a1 === undefined) return arr;
	arr.push(a1);

	const a2 = record.peerKey;
	if (a2 === undefined) return arr;
	arr.push(a2);

	return arr;
}

// '@ghostdrive/joins-by-session'
const index6 = {
	name: '@ghostdrive/joins-by-session',
	version: 1,
	id: 6,
	encodeKey(record) {
		return index6_key.encode(index6_indexify(record));
	},
	encodeKeyRange({ gt, lt, gte, lte } = {}) {
		return index6_key.encodeRange({
			gt: gt ? index6_indexify(gt) : null,
			lt: lt ? index6_indexify(lt) : null,
			gte: gte ? index6_indexify(gte) : null,
			lte: lte ? index6_indexify(lte) : null
		});
	},
	encodeValue: (record) => index6.collection.encodeKey(record),
	encodeIndexKeys(record, context) {
		return [index6_key.encode([record.sessionId, record.sessionId, record.peerKey])];
	},
	reconstruct: (keyBuf, valueBuf) => valueBuf,
	offset: collection3.indexes.length,
	collection: collection3
};
collection3.indexes.push(index6);

const collections = [collection0, collection1, collection2, collection3];

const indexes = [index4, index5, index6];

export default { versions, collections, indexes, resolveCollection, resolveIndex };

function resolveCollection(name) {
	switch (name) {
		case '@ghostdrive/sessions':
			return collection0;
		case '@ghostdrive/registrations':
			return collection1;
		case '@ghostdrive/invites':
			return collection2;
		case '@ghostdrive/joins':
			return collection3;
		default:
			return null;
	}
}

function resolveIndex(name) {
	switch (name) {
		case '@ghostdrive/registrations-by-session':
			return index4;
		case '@ghostdrive/invites-by-session':
			return index5;
		case '@ghostdrive/joins-by-session':
			return index6;
		default:
			return null;
	}
}
