// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @ghostdrive/session
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.buffer.preencode(state, m.icon)
    c.uint.preencode(state, m.createdAt)
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.remoteKey) c.string.preencode(state, m.remoteKey)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.remoteKey) ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.buffer.encode(state, m.icon)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (version >= 2 && m.remoteKey) c.string.encode(state, m.remoteKey)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.uint.decode(state)
    const flags = state.start < state.end ? c.uint.decode(state) : 0

    return {
      id: r0,
      name: r1,
      icon: r2,
      createdAt: r3,
      remoteKey: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @ghostdrive/registration
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.sessionId)
    c.string.preencode(state, m.target)
    c.string.preencode(state, m.type)
    c.uint.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.sessionId)
    c.string.encode(state, m.target)
    c.string.encode(state, m.type)
    c.uint.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)

    return {
      sessionId: r0,
      target: r1,
      type: r2,
      createdAt: r3
    }
  }
}

// @ghostdrive/invite
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.sessionId)
    c.string.preencode(state, m.capKey)
    state.end++ // max flag is 1 so always one byte
    c.uint.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags = m.used ? 1 : 0

    c.string.encode(state, m.sessionId)
    c.string.encode(state, m.capKey)
    c.uint.encode(state, flags)
    c.uint.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      sessionId: r0,
      capKey: r1,
      used: (flags & 1) !== 0,
      createdAt: c.uint.decode(state)
    }
  }
}

// @ghostdrive/join
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.sessionId)
    c.string.preencode(state, m.peerKey)
    c.string.preencode(state, m.capKey)
    c.uint.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.sessionId)
    c.string.encode(state, m.peerKey)
    c.string.encode(state, m.capKey)
    c.uint.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)

    return {
      sessionId: r0,
      peerKey: r1,
      capKey: r2,
      createdAt: r3
    }
  }
}

// @ghostdrive/session/hyperdb#0
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.buffer.preencode(state, m.icon)
    c.uint.preencode(state, m.createdAt)
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.remoteKey) c.string.preencode(state, m.remoteKey)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.remoteKey) ? 1 : 0

    c.string.encode(state, m.name)
    c.buffer.encode(state, m.icon)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (version >= 2 && m.remoteKey) c.string.encode(state, m.remoteKey)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.uint.decode(state)
    const flags = state.start < state.end ? c.uint.decode(state) : 0

    return {
      id: null,
      name: r1,
      icon: r2,
      createdAt: r3,
      remoteKey: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @ghostdrive/registration/hyperdb#1
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.type)
    c.uint.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.type)
    c.uint.encode(state, m.createdAt)
  },
  decode(state) {
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)

    return {
      sessionId: null,
      target: null,
      type: r2,
      createdAt: r3
    }
  }
}

// @ghostdrive/invite/hyperdb#2
const encoding6 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
    c.uint.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags = m.used ? 1 : 0

    c.uint.encode(state, flags)
    c.uint.encode(state, m.createdAt)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      sessionId: null,
      capKey: null,
      used: (flags & 1) !== 0,
      createdAt: c.uint.decode(state)
    }
  }
}

// @ghostdrive/join/hyperdb#3
const encoding7 = {
  preencode(state, m) {
    c.string.preencode(state, m.capKey)
    c.uint.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.capKey)
    c.uint.encode(state, m.createdAt)
  },
  decode(state) {
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)

    return {
      sessionId: null,
      peerKey: null,
      capKey: r2,
      createdAt: r3
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@ghostdrive/session':
      return encoding0
    case '@ghostdrive/registration':
      return encoding1
    case '@ghostdrive/invite':
      return encoding2
    case '@ghostdrive/join':
      return encoding3
    case '@ghostdrive/session/hyperdb#0':
      return encoding4
    case '@ghostdrive/registration/hyperdb#1':
      return encoding5
    case '@ghostdrive/invite/hyperdb#2':
      return encoding6
    case '@ghostdrive/join/hyperdb#3':
      return encoding7
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
